jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build the project
        run: npm run build

      - name: List files in the build directory
        run: ls -la dist

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Debug Netlify Site ID
        run: |
          echo "Site ID: $NETLIFY_SITE_ID"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Netlify (PR preview)
        if: github.event_name == 'pull_request'
        run: netlify deploy --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID --dir=dist --message="Deploy preview"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NEXT_PUBLIC_API_URL_LOCAL: ${{ secrets.NEXT_PUBLIC_API_URL_LOCAL }}
          NEXT_PUBLIC_API_URL_PRODUCTION: ${{ secrets.NEXT_PUBLIC_API_URL_PRODUCTION }}
          NEXT_PUBLIC_API_URL_STAGING: ${{ secrets.NEXT_PUBLIC_API_URL_STAGING }}
          NODE_ENV: ${{ secrets.NODE_ENV }}

      - name: Deploy to Netlify (Final build after merge with clean cache)
        if: github.event_name == 'push'
        run: |
          netlify build && netlify deploy --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID --dir=dist --message="Final production deploy"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NEXT_PUBLIC_API_URL_LOCAL: ${{ secrets.NEXT_PUBLIC_API_URL_LOCAL }}
          NEXT_PUBLIC_API_URL_PRODUCTION: ${{ secrets.NEXT_PUBLIC_API_URL_PRODUCTION }}
          NEXT_PUBLIC_API_URL_STAGING: ${{ secrets.NEXT_PUBLIC_API_URL_STAGING }}
          NODE_ENV: ${{ secrets.NODE_ENV }}

      - name: Run Tests
        run: npm test

      - name: Run Code Style Checks
        run: npm run code-style-check
